# Generated by Django 3.2 on 2022-06-07 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0007_auto_20220607_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='temp_id',
            new_name='id',
        ),
    ]
