# Generated by Django 3.2 on 2022-06-07 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0010_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('700badac-48be-43dd-89df-66f0684bf5f1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
