# Generated by Django 3.2 on 2022-06-07 01:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0011_alter_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6afb25fa-d35d-4945-a751-a9d786e5cb80'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
