# Generated by Django 3.2 on 2022-06-07 01:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0012_auto_20220607_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uuid',
        ),
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3921c4a6-ea6e-4489-aeed-a7563350ad08'), editable=False, primary_key=True, serialize=False),
        ),
    ]
