# Generated by Django 3.2 on 2022-06-07 02:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('25ee8489-a71d-4f62-b4a7-51bf5fdab0f6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
