# Generated by Django 3.2 on 2022-06-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0001_initial'),
    ]

    operations = [
    ]
