# Generated by Django 3.2 on 2022-06-07 01:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f856b044-0d7c-4046-8c8b-f1b61e41d6df'), editable=False, primary_key=True, serialize=False),
        ),
    ]
