# Generated by Django 3.2 on 2022-06-07 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0002_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('991080c5-214e-4068-a765-234087f2b331'), editable=False, primary_key=True, serialize=False),
        ),
    ]
