# Generated by Django 3.2 on 2022-06-07 01:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0003_auto_20220607_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7abf737d-0b25-4980-a26a-00b04a665b3b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
