# Generated by Django 3.2 on 2022-06-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0004_auto_20220606_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
