# Generated by Django 3.2 on 2022-06-07 02:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0004_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6aa5e23a-3c18-4a9a-9f94-5e5d4000c14b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
