# Generated by Django 3.2 on 2022-06-07 02:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0005_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('58f4a4e1-c96b-4900-b326-cee6f1353d13'), editable=False, primary_key=True, serialize=False),
        ),
    ]
