# Generated by Django 3.2 on 2022-06-07 01:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0005_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d87f524-2d3c-4fcd-8266-31dff7698589'), editable=False, primary_key=True, serialize=False),
        ),
    ]
