# Generated by Django 3.2 on 2022-06-07 01:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0006_alter_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b18cd947-b8da-4628-ba73-b3183c63cd9c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
