# Generated by Django 3.2 on 2022-06-07 02:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0007_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4ff1a040-8f39-4651-9d94-fc2f58daf4a2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
