# Generated by Django 3.2 on 2022-06-07 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0008_auto_20220607_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('892d3d11-d918-4bb0-999e-8ec998103d30'), editable=False, primary_key=True, serialize=False),
        ),
    ]
