# Generated by Django 3.2 on 2022-06-07 02:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0009_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('35c1b15d-98b4-4e0b-8e24-48b342eb4d52'), editable=False, primary_key=True, serialize=False),
        ),
    ]
