# Generated by Django 3.2 on 2022-06-07 02:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0010_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb1e7c78-985e-41b5-9b32-4132cfb9f14f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
