# Generated by Django 3.2 on 2022-06-07 02:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0011_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9e7e802-f964-4593-80ae-452c792573cc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
