# Generated by Django 3.2 on 2022-06-07 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0012_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0ce166e3-54d6-42de-8782-bd902802b6b9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
