# Generated by Django 3.2 on 2022-06-07 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picwise', '0013_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63defa6a-13af-42a6-ab69-d78e6e90a1d7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
